---
- hosts: "{{ my_droplet_ip }}"
  remote_user: mattp

  vars_files:
          - var_secret.yml
          - var_public.yml

  vars:
          container_name: matt_cv_web
          container_network: matt_network

  tasks:
          - name: Login To Docker Hub
            docker_login:
                    registry: "{{ docker_hub_repo }}"
                    username: pigstah
                    password: "{{ docker_hub_password }}"

          - name: Pull Image From Docker Hub
            shell: docker pull docker.io/pigstah/flask:{{ BUILD_VERSION }}
            when: BUILD_UPDATE

          - name: Stop Running Container
            shell: docker stop {{ container_name }}
            when: BUILD_UPDATE

          - name: Remove Current Container
            shell: docker rm {{ container_name }}
            when: BUILD_UPDATE

          - name: Run Docker Container
            shell: docker run -d -it -p 5000:5000 -v /etc/letsencrypt/live:/matt_web_cv/etc/ssl/ --name {{ container_name }} --network={{ container_network }} --restart=always docker.io/pigstah/flask:{{ BUILD_VERSION }}
            
              # name: Mount Certs
              # shell: docker run -v /etc/letsencrypt/live/matthewpigram.co.uk:/matt_web_cv/etc/ssl/ -d pigstah/flask:{{ BUILD_VERSION }}
